/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'john' at '3/2/17 3:50 PM' with Gradle 2.14.1
 *
 * @author john, @date 3/2/17 3:50 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
